### ISSUE TITLE
crashes when first indexing

### ISSUE THREAD

**Issue by krodelabestiole** [blomstra/flarum-ext-search#8]
hello, I try to Index a huge forum, but at some point it fails and can't go on indexing.

it seems to start from the beginning when I launch it again...

```
PHP Fatal error:  Uncaught TypeError: Blomstra\Search\Seeders\Seeder::groupsForDiscussion(): Argument #1 ($discussion) must be of type Flarum\Discussion\Discussion, null given, called in /opt/flarum/vendor/blomstra/search/src/Seeders/CommentSeeder.php on line 69 and defined in /opt/flarum/vendor/blomstra/search/src/Seeders/Seeder.php:27
Stack trace:
#0 /opt/flarum/vendor/blomstra/search/src/Seeders/CommentSeeder.php(69): Blomstra\Search\Seeders\Seeder->groupsForDiscussion()
#1 /opt/flarum/vendor/blomstra/search/src/Jobs/SavingJob.php(18): Blomstra\Search\Seeders\CommentSeeder->toDocument()
#2 [internal function]: Blomstra\Search\Jobs\SavingJob->Blomstra\Search\Jobs\{closure}()
#3 /opt/flarum/vendor/illuminate/collections/Collection.php(695): array_map()
#4 /opt/flarum/vendor/illuminate/database/Eloquent/Collection.php(350): Illuminate\Support\Collection->map()
#5 /opt/flarum/vendor/blomstra/search/src/Jobs/SavingJob.php(24): Illuminate\Database\Eloquent\Collection->map()
#6 /opt/flarum/vendor/illuminate/container/BoundMethod.php(36): Blomstra\Search\Jobs\SavingJob->handle()
#7 /opt/flarum/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /opt/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /opt/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /opt/flarum/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call()
#11 /opt/flarum/vendor/illuminate/bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#12 /opt/flarum/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#13 /opt/flarum/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /opt/flarum/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#15 /opt/flarum/vendor/illuminate/queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#16 /opt/flarum/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#17 /opt/flarum/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /opt/flarum/vendor/illuminate/queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#19 /opt/flarum/vendor/illuminate/queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#20 /opt/flarum/vendor/illuminate/queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#21 /opt/flarum/vendor/illuminate/queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#22 /opt/flarum/vendor/illuminate/queue/Queue.php(57): Illuminate\Queue\SyncQueue->push()
#23 /opt/flarum/vendor/blomstra/search/src/Commands/BuildCommand.php(131): Illuminate\Queue\Queue->pushOn()
#24 /opt/flarum/vendor/illuminate/container/BoundMethod.php(36): Blomstra\Search\Commands\BuildCommand->handle()
#25 /opt/flarum/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /opt/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#27 /opt/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#28 /opt/flarum/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call()
#29 /opt/flarum/vendor/illuminate/console/Command.php(136): Illuminate\Container\Container->call()
#30 /opt/flarum/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#31 /opt/flarum/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#32 /opt/flarum/vendor/symfony/console/Application.php(1042): Illuminate\Console\Command->run()
#33 /opt/flarum/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#34 /opt/flarum/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#35 /opt/flarum/vendor/flarum/core/src/Console/Server.php(42): Symfony\Component\Console\Application->run()
#36 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#37 {main}
  thrown in /opt/flarum/vendor/blomstra/search/src/Seeders/Seeder.php on line 27
```

**Comment by luceos** [comment]
I must have missed this in my notifications.. Did you ever fix this?
